Config                            = {}
Config.DrawDistance               = 100
Config.MarkerColor                = {r = 255, g = 255, b = 0}
Config.ResellPercentage           = 80
Config.SuleymanPara 			  = 1.5


Config.PlateLetters  = 3
Config.PlateNumbers  = 3
Config.PlateUseSpace = true

Config.testCarTime = 50
Config.testCarPrice = 25


Config.ShopInside = vector4(-75.776741027832, -821.27557373047, 284.03159790039, 193.0)
Config.BuyCoord = vector4(-31.59, -1090.51, 26.0, 325.98)
Config.DealerCarSpawn = vector4(-31.59, -1090.51, 26.0, 325.98)
Config.denemenokta = vector4(-1953.81, 2827.54, 32.04, 59.82)
Config.denemenoktabitis = vector4(-29.91, -1103.48, 26.42, 68.13)



Config.Vehicles = {
	["Motosiklet"] = {
		[`carbonrs`] = {
			["name"] = "carbonrs",
			["model"] = "carbonrs",
			["count"] = 2,
			["price"] = 65000,
		},
		[`faggio2`] = {
			["name"] = "faggio2",
			["model"] = "faggio2",
			["count"] = 10,
			["price"] = 1000,
		},
		[`bf400`] = {
			["name"] = "bf400",
			["model"] = "bf400",
			["count"] = 2,
			["price"] = 30000,
		},
		[`fcr`] = {
			["name"] = "fcr",
			["model"] = "fcr",
			["count"] = 2,
			["price"] = 23000,
		},
		[`Gargoyle`] = {
			["name"] = "Gargoyle",
			["model"] = "Gargoyle",
			["count"] = 2,
			["price"] = 45000,
		},
		[`sovereign`] = {
			["name"] = "sovereign",
			["model"] = "sovereign",
			["count"] = 2,
			["price"] = 65000,
		},
		[`hakuchou`] = {
			["name"] = "hakuchou",
			["model"] = "hakuchou",
			["count"] = 2,
			["price"] = 85000,
		},
		[`akuma`] = {
			["name"] = "akuma",
			["model"] = "akuma",
			["count"] = 2,
			["price"] = 35000,
		},
		[`enduro`] = {
			["name"] = "enduro",
			["model"] = "enduro",
			["count"] = 10,
			["price"] = 15000,
		},
		[`daemon`] = {
			["name"] = "daemon",
			["model"] = "daemon",
			["count"] = 2,
			["price"] = 65000,
		},
		[`bagger`] = {
			["name"] = "bagger",
			["model"] = "bagger",
			["count"] = 10,
			["price"] = 20000,
		},
		[`bati`] = {
			["name"] = "bati",
			["model"] = "bati",
			["count"] = 2,
			["price"] = 55000,
		},
		[`nightblade`] = {
			["name"] = "nightblade",
			["model"] = "nightblade",
			["count"] = 2,
			["price"] = 77000,
		},
		[`faggio3`] = {
			["name"] = "faggio3",
			["model"] = "faggio3",
			["count"] = 10,
			["price"] = 1250,
		},
		[`ınnovation`] = {
			["name"] = "ınnovation",
			["model"] = "ınnovation",
			["count"] = 2,
			["price"] = 50000,
		},
		[`diablous`] = {
			["name"] = "diablous",
			["model"] = "diablous",
			["count"] = 2,
			["price"] = 47000,
		},
		[`wolfsbane`] = {
			["name"] = "wolfsbane",
			["model"] = "wolfsbane",
			["count"] = 2,
			["price"] = 53000,
		},
		[`nemesis`] = {
			["name"] = "nemesis",
			["model"] = "nemesis",
			["count"] = 2,
			["price"] = 30000,
		},
		[`vader`] = {
			["name"] = "vader",
			["model"] = "vader",
			["count"] = 2,
			["price"] = 32000,
		},
		[`double`] = {
			["name"] = "double",
			["model"] = "double",
			["count"] = 2,
			["price"] = 60000,
		},
		[`double`] = {
			["name"] = "double",
			["model"] = "double",
			["count"] = 2,
			["price"] = 60000,
		},
		[`faggio`] = {
			["name"] = "faggio",
			["model"] = "faggio",
			["count"] = 10,
			["price"] = 1500,
		},
		[`sanchez2`] = {
			["name"] = "sanchez2",
			["model"] = "sanchez2",
			["count"] = 10,
			["price"] = 33000,
		},
		[`avarus`] = {
			["name"] = "avarus",
			["model"] = "avarus",
			["count"] = 2,
			["price"] = 45000,
		},
	},
	["Bisiklet"] = {
		[`tribke`] = {
			["name"] = "tribike",
			["model"] = "tribike",
			["count"] = 500000,
			["price"] = 350,
		},
		[`tribike2`] = {
			["name"] = "tribike-2",
			["model"] = "tribike2",
			["count"] = 500000,
			["price"] = 250,
		},
		[`bmx`] = {
			["name"] = "bmx",
			["model"] = "bmx",
			["count"] = 500000,
			["price"] = 300,
		},
		[`cruiser`] = {
			["name"] = "cruiser",
			["model"] = "cruiser",
			["count"] = 500000,
			["price"] = 500,
		},
		[`tribike3`] = {
			["name"] = "tribike-3",
			["model"] = "tribike3",
			["count"] = 500000,
			["price"] = 300,
		},
		[`fixter`] = {
			["name"] = "fixter",
			["model"] = "fixter",
			["count"] = 500000,
			["price"] = 250,
		},
		[`scorcher`] = {
			["name"] = "scorcher",
			["model"] = "scorcher",
			["count"] = 500000,
			["price"] = 450,
		},
		
	},
	["A Class"] = {
		[`euros`] = {
			["name"] = "euros",
			["model"] = "euros",
			["count"] = 1,
			["price"] = 350000,
		},
		[`calico`] = {
			["name"] = "calico",
			["model"] = "calico",
			["count"] = 1,
			["price"] = 325000,
		},
		[`carbonizzare`] = {
			["name"] = "carbonizzare",
			["model"] = "carbonizzare",
			["count"] = 1,
			["price"] = 285000,
		},
		[`panthere`] = {
			["name"] = "panthere",
			["model"] = "panthere",
			["count"] = 1,
			["price"] = 325000,
		},
		[`sugoi`] = {
			["name"] = "sugoi",
			["model"] = "sugoi",
			["count"] = 2,
			["price"] = 185000,
		},
		[`drafter`] = {
			["name"] = "drafter",
			["model"] = "drafter",
			["count"] = 2,
			["price"] = 420000,
		},
		[`jester3`] = {
			["name"] = "jester3",
			["model"] = "jester3",
			["count"] = 2,
			["price"] = 250000,
		},
		 [`dominator7`] = {
		 	["name"] = "dominator7",
		 	["model"] = "dominator7",
	 	["count"] = 2,
	 	["price"] = 325000,
		},
		[`elegy`] = {
			["name"] = "elegy",
			["model"] = "elegy",
			["count"] = 2,
			["price"] = 360000,
		},
		[`sultan2`] = {
			["name"] = "sultan2",
			["model"] = "sultan2",
			["count"] = 2,
			["price"] = 325000,
		},
		 [`vigero2`] = {
		 	["name"] = "vigero2",
		 	["model"] = "vigero2",
		 	["count"] = 2,
		 	["price"] = 400000,
		 },
		[`buffalo4`] = {
			["name"] = "buffalo4",
			["model"] = "buffalo4",
			["count"] = 2,
			["price"] = 370000,
		},
		[`dominator`] = {
			["name"] = "dominator",
			["model"] = "dominator",
			["count"] = 2,
			["price"] = 120000,
		},
		[`rebla`] = {
			["name"] = "rebla",
			["model"] = "rebla",
			["count"] = 2,
			["price"] = 130000,
		},
		[`issi7`] = {
			["name"] = "issi7",
			["model"] = "issi7",
			["count"] = 0,
			["price"] = 140000,
		},
		[`jester`] = {
			["name"] = "jester",
			["model"] = "jester",
			["count"] = 2,
			["price"] = 200000,
		},
		[`lynx`] = {
			["name"] = "lynx",
			["model"] = "lynx",
			["count"] = 3,
			["price"] = 180000,
		},
		[`banshee`] = {
			["name"] = "banshee",
			["model"] = "banshee",
			["count"] = 2,
			["price"] = 200000,
		},
		[`ninef`] = {
			["name"] = "ninef",
			["model"] = "ninef",
			["count"] = 2,
			["price"] = 200000,
		},
		[`schafter4`] = {
			["name"] = "schafter4",
			["model"] = "schafter4",
			["count"] = 2,
			["price"] = 110000,
		},
		[`seven70`] = {
			["name"] = "seven70",
			["model"] = "seven70",
			["count"] = 0,
			["price"] = 185000,
		},
		[`infernus`] = {
			["name"] = "infernus",
			["model"] = "infernus",
			["count"] = 2,
			["price"] = 225000,
		},
		[`sultan`] = {
			["name"] = "sultan",
			["model"] = "sultan",
			["count"] = 2,
			["price"] = 160000,
		},
		[`futo2`] = {
			["name"] = "futo2",
			["model"] = "futo2",
			["count"] = 2,
			["price"] = 155000,
		},
		[`vectre`] = {
			["name"] = "vectre",
			["model"] = "vectre",
			["count"] = 1,
			["price"] = 325000,
		},
		[`penumbra2`] = {
			["name"] = "penumbra2",
			["model"] = "penumbra2",
			["count"] = 1,
			["price"] = 265000,
		},
		[`paragon`] = {
			["name"] = "paragon",
			["model"] = "paragon",
			["count"] = 1,
			["price"] = 400000,
		},
		[`jugular`] = {
			["name"] = "jugular",
			["model"] = "jugular",
			["count"] = 1,
			["price"] = 350000,
		},
		[`imorgon`] = {
			["name"] = "imorgon",
			["model"] = "imorgon",
			["count"] = 1,
			["price"] = 385000,
		},
		[`neon`] = {
			["name"] = "neon",
			["model"] = "neon",
			["count"] = 1,
			["price"] = 400000,
		},
		[`furoregt`] = {
			["name"] = "furoregt",
			["model"] = "furoregt",
			["count"] = 1,
			["price"] = 245000,
		},
		[`khamelion`] = {
			["name"] = "khamelion",
			["model"] = "khamelion",
			["count"] = 1,
			["price"] = 300000,
		},
		[`massacro`] = {
			["name"] = "massacro",
			["model"] = "massacro",
			["count"] = 1,
			["price"] = 285000,
		},
		[`schwarzer`] = {
			["name"] = "schwarzer",
			["model"] = "schwarzer",
			["count"] = 1,
			["price"] = 285000,
		},
		

		
		
	},
	["B Class"] = {
		[`baller2`] = {
			["name"] = "baller2",
			["model"] = "baller2",
			["count"] = 2,
			["price"] = 125000,
		},
		[`chino`] = {
			["name"] = "chino",
			["model"] = "chino",
			["count"] = 2,
			["price"] = 10000,
		},
		[`fusilade`] = {
			["name"] = "fusilade",
			["model"] = "fusilade",
			["count"] = 2,
			["price"] = 55000,
		},
		[`gauntlet3`] = {
			["name"] = "gauntlet3",
			["model"] = "gauntlet3",
			["count"] = 2,
			["price"] = 90000,
		},
		[`dukes`] = {
			["name"] = "dukes",
			["model"] = "dukes",
			["count"] = 2,
			["price"] = 27000,
		},
		[`alpha`] = {
			["name"] = "alpha",
			["model"] = "alpha",
			["count"] = 2,
			["price"] = 60000,
		},
		[`bjxl`] = {
			["name"] = "bjxl",
			["model"] = "bjxl",
			["count"] = 2,
			["price"] = 100000,
		},
		[`sentinel2`] = {
			["name"] = "sentinel2",
			["model"] = "sentinel2",
			["count"] = 2,
			["price"] = 65000,
		},
		[`savestra`] = {
			["name"] = "savestra",
			["model"] = "savestra",
			["count"] = 2,
			["price"] = 85000,
		},
		[`tampa`] = {
			["name"] = "tampa",
			["model"] = "tampa",
			["count"] = 2,
			["price"] = 50000,
		},
		[`sentinel3`] = {
			["name"] = "sentinel3",
			["model"] = "sentinel3",
			["count"] = 2,
			["price"] = 75000,
		},
		[`xls`] = {
			["name"] = "xls",
			["model"] = "xls",
			["count"] = 2,
			["price"] = 100000,
		},
		[`seminole`] = {
			["name"] = "seminole",
			["model"] = "seminole",
			["count"] = 2,
			["price"] = 80000,
		},
		[`oracle`] = {
			["name"] = "oracle",
			["model"] = "oracle",
			["count"] = 2,
			["price"] = 70000,
		},
		[`sentinel`] = {
			["name"] = "sentinel",
			["model"] = "sentinel",
			["count"] = 2,
			["price"] = 13000,
		},
		[`tulip`] = {
			["name"] = "tulip",
			["model"] = "tulip",
			["count"] = 2,
			["price"] = 65000,
		},
		[`picador`] = {
			["name"] = "picador",
			["model"] = "picador",
			["count"] = 2,
			["price"] = 60000,
		},
		[`rapidgt2`] = {
			["name"] = "rapidgt2",
			["model"] = "rapidgt2",
			["count"] = 2,
			["price"] = 70000,
		},
		[`zion3`] = {
			["name"] = "zion3",
			["model"] = "zion3",
			["count"] = 2,
			["price"] = 50000,
		},
		[`fugitive`] = {
			["name"] = "fugitive",
			["model"] = "fugitive",
			["count"] = 2,
			["price"] = 65000,
		},
		[`stalion`] = {
			["name"] = "stalion",
			["model"] = "stalion",
			["count"] = 2,
			["price"] = 17000,
		},
		[`rapidgt3`] = {
			["name"] = "rapidgt3",
			["model"] = "rapidgt3",
			["count"] = 2,
			["price"] = 40000,
		},
		[`rocoto`] = {
			["name"] = "rocoto",
			["model"] = "rocoto",
			["count"] = 2,
			["price"] = 83000,
		},
		[`schafter2`] = {
			["name"] = "schafter2",
			["model"] = "schafter2",
			["count"] = 2,
			["price"] = 70000,
		},
		[`rapidgt`] = {
			["name"] = "rapidgt",
			["model"] = "rapidgt",
			["count"] = 2,
			["price"] = 60000,
		},
		[`Flashgt`] = {
			["name"] = "flashgt",
			["model"] = "flashgt",
			["count"] = 2,
			["price"] = 85000,
		},
		[`prairie`] = {
			["name"] = "prairie",
			["model"] = "prairie",
			["count"] = 2,
			["price"] = 36500,
		},
		[`felon`] = {
			["name"] = "felon",
			["model"] = "felon",
			["count"] = 2,
			["price"] = 75000,
		},
		[`gauntlet5`] = {
			["name"] = "gauntlet5",
			["model"] = "gauntlet5",
			["count"] = 2,
			["price"] = 150000,
		},
		[`clique`] = {
			["name"] = "clique",
			["model"] = "clique",
			["count"] = 2,
			["price"] = 85000,
		},
		[`oracle2`] = {
			["name"] = "oracle2",
			["model"] = "oracle2",
			["count"] = 2,
			["price"] = 85000,
		},
		[`vigero`] = {
			["name"] = "vigero",
			["model"] = "vigero",
			["count"] = 2,
			["price"] = 30000,
		},
		[`gt500`] = {
			["name"] = "gt500",
			["model"] = "gt500",
			["count"] = 2,
			["price"] = 85000,
		},
		[`patriot`] = {
			["name"] = "patriot",
			["model"] = "patriot",
			["count"] = 2,
			["price"] = 83000,
		},
		[`voltic`] = {
			["name"] = "voltic",
			["model"] = "voltic",
			["count"] = 2,
			["price"] = 150000,
		},
		[`zion`] = {
			["name"] = "zion",
			["model"] = "zion",
			["count"] = 2,
			["price"] = 70000,
		},
		[`gauntlet`] = {
			["name"] = "gauntlet",
			["model"] = "gauntlet",
			["count"] = 2,
			["price"] = 65000,
		},
		[`buffalo`] = {
			["name"] = "buffalo",
			["model"] = "buffalo",
			["count"] = 2,
			["price"] = 84000,
		},
		[`tailgater`] = {
			["name"] = "tailgater",
			["model"] = "tailgater",
			["count"] = 2,
			["price"] = 55000,
		},
		[`penumbra`] = {
			["name"] = "penumbra",
			["model"] = "penumbra",
			["count"] = 2,
			["price"] = 75000,
		},
		[`mesa3`] = {
			["name"] = "mesa3",
			["model"] = "mesa3",
			["count"] = 2,
			["price"] = 85000,
		},
		[`phoenix`] = {
			["name"] = "phoenix",
			["model"] = "phoenix",
			["count"] = 2,
			["price"] = 65000,
		},
		[`exemplar`] = {
			["name"] = "exemplar",
			["model"] = "exemplar",
			["count"] = 2,
			["price"] = 68000,
		},
		[`blista`] = {
			["name"] = "blista",
			["model"] = "blista",
			["count"] = 2,
			["price"] = 50000,
		},
		[`furoregt`] = {
			["name"] = "furoregt",
			["model"] = "furoregt",
			["count"] = 2,
			["price"] = 90000,
		},
		[`ımpaler`] = {
			["name"] = "ımpaler",
			["model"] = "ımpaler",
			["count"] = 2,
			["price"] = 16000,
		},
		[`cavalcade2`] = {
			["name"] = "cavalcade2",
			["model"] = "cavalcade2",
			["count"] = 2,
			["price"] = 75000,
		},
		[`sabregt`] = {
			["name"] = "sabregt",
			["model"] = "sabregt",
			["count"] = 2,
			["price"] = 65000,
		},
		[`landstalker2`] = {
			["name"] = "landstalker2",
			["model"] = "landstalker2",
			["count"] = 2,
			["price"] = 93000,
		},
		[`fq2`] = {
			["name"] = "fq2",
			["model"] = "fq2",
			["count"] = 2,
			["price"] = 82500,
		},
		[`kamacho`] = {
			["name"] = "kamacho",
			["model"] = "kamacho",
			["count"] = 2,
			["price"] = 100000,
		},
		[`blade`] = {
			["name"] = "blade",
			["model"] = "blade",
			["count"] = 2,
			["price"] = 13000,
		},
		[`felon2`] = {
			["name"] = "felon2",
			["model"] = "felon2",
			["count"] = 2,
			["price"] = 80000,
		},
		[`gresley`] = {
			["name"] = "gresley",
			["model"] = "gresley",
			["count"] = 2,
			["price"] = 75000,
		},
		[`mamba`] = {
			["name"] = "mamba",
			["model"] = "mamba",
			["count"] = 2,
			["price"] = 70000,
		},
		[`schwarzer`] = {
			["name"] = "schwarzer",
			["model"] = "schwarzer",
			["count"] = 2,
			["price"] = 62000,
		},
		[`zion2`] = {
			["name"] = "zion2",
			["model"] = "zion2",
			["count"] = 2,
			["price"] = 78000,
		},
		[`ruiner`] = {
			["name"] = "ruiner",
			["model"] = "ruiner",
			["count"] = 2,
			["price"] = 60000,
		},
		[`faction`] = {
			["name"] = "faction",
			["model"] = "faction",
			["count"] = 2,
			["price"] = 17000,
		},
		[`feltzer3`] = {
			["name"] = "feltzer3",
			["model"] = "feltzer3",
			["count"] = 2,
			["price"] = 170000,
		},
		
	},
	["C Class"] = {
		[`virgo`] = {
			["name"] = "virgo",
			["model"] = "virgo",
			["count"] = 2,
			["price"] = 8000,
		},
		[`glendale`] = {
			["name"] = "glendale",
			["model"] = "glendale",
			["count"] = 2,
			["price"] = 30000,
		},
		[`btype`] = {
			["name"] = "btype",
			["model"] = "btype",
			["count"] = 2,
			["price"] = 150000,
		},
		[`sabregt2`] = {
			["name"] = "sabregt2",
			["model"] = "sabregt2",
			["count"] = 2,
			["price"] = 35000,
		},
		[`dynasty`] = {
			["name"] = "dynasty",
			["model"] = "dynasty",
			["count"] = 2,
			["price"] = 85000,
		},
		[`huntley`] = {
			["name"] = "huntley",
			["model"] = "huntley",
			["count"] = 2,
			["price"] = 40000,
		},
		[`moonbeam`] = {
			["name"] = "moonbeam",
			["model"] = "moonbeam",
			["count"] = 2,
			["price"] = 10335,
		},
		[`slamvan`] = {
			["name"] = "slamvan",
			["model"] = "slamvan",
			["count"] = 2,
			["price"] = 28335,
		},
		[`slamvan2`] = {
			["name"] = "slamvan2",
			["model"] = "slamvan2",
			["count"] = 2,
			["price"] = 30000,
		},
		[`rhapsody`] = {
			["name"] = "rhapsody",
			["model"] = "rhapsody",
			["count"] = 2,
			["price"] = 17535,
		},
		[`habanero`] = {
			["name"] = "habanero",
			["model"] = "habanero",
			["count"] = 2,
			["price"] = 30000,
		},
		[`ıntruder`] = {
			["name"] = "ıntruder",
			["model"] = "ıntruder",
			["count"] = 2,
			["price"] = 45000,
		},
		[`blista2`] = {
			["name"] = "blista2",
			["model"] = "blista2",
			["count"] = 2,
			["price"] = 20000,
		},
		[`pigalle`] = {
			["name"] = "pigalle",
			["model"] = "pigalle",
			["count"] = 2,
			["price"] = 10000,
		},
		[`bfinjection`] = {
			["name"] = "bfinjection",
			["model"] = "bfinjection",
			["count"] = 2,
			["price"] = 50000,
		},
		[`landstalker`] = {
			["name"] = "landstalker",
			["model"] = "landstalker",
			["count"] = 2,
			["price"] = 67535,
		},
		[`serrano`] = {
			["name"] = "serrano",
			["model"] = "serrano",
			["count"] = 2,
			["price"] = 50000,
		},
		[`brioso2`] = {
			["name"] = "brioso2",
			["model"] = "brioso2",
			["count"] = 2,
			["price"] = 6500,
		},
		[`weevil`] = {
			["name"] = "weevil",
			["model"] = "weevil",
			["count"] = 2,
			["price"] = 55000,
		},
		[`rancher`] = {
			["name"] = "rancher",
			["model"] = "rancher",
			["count"] = 2,
			["price"] = 57000,
		},
		[`streiter`] = {
			["name"] = "streiter",
			["model"] = "streiter",
			["count"] = 2,
			["price"] = 71235,
		},
		[`washington`] = {
			["name"] = "washington",
			["model"] = "washington",
			["count"] = 2,
			["price"] = 20000,
		},
		[`moonbeam2`] = {
			["name"] = "moonbeam2",
			["model"] = "moonbeam2",
			["count"] = 2,
			["price"] = 14500,
		},
		[`voodoo`] = {
			["name"] = "voodoo",
			["model"] = "voodoo",
			["count"] = 2,
			["price"] = 7000,
		},
		[`cavalcade`] = {
			["name"] = "cavalcade",
			["model"] = "cavalcade",
			["count"] = 2,
			["price"] = 62500,
		},
		[`futo`] = {
			["name"] = "futo",
			["model"] = "futo",
			["count"] = 2,
			["price"] = 72000,
		},
		[`virgo`] = {
			["name"] = "virgo",
			["model"] = "virgo",
			["count"] = 2,
			["price"] = 8500,
		},
		[`buccaneer2`] = {
			["name"] = "buccaneer2",
			["model"] = "buccaneer2",
			["count"] = 4,
			["price"] = 14500,
		},
		[`dilettante`] = {
			["name"] = "dilettante",
			["model"] = "dilettante",
			["count"] = 2,
			["price"] = 40000,
		},
		[`rebel2`] = {
			["name"] = "rebel2",
			["model"] = "rebel2",
			["count"] = 2,
			["price"] = 65000,
		},
		[`glendale2`] = {
			["name"] = "glendale2",
			["model"] = "glendale2",
			["count"] = 2,
			["price"] = 35000,
		},
		[`blazer4`] = {
			["name"] = "blazer4",
			["model"] = "blazer4",
			["count"] = 2,
			["price"] = 20000,
		},
		[`primo2`] = {
			["name"] = "primo2",
			["model"] = "primo2",
			["count"] = 2,
			["price"] = 33000,
		},
		[`granger`] = {
			["name"] = "granger",
			["model"] = "granger",
			["count"] = 2,
			["price"] = 85000,
		},
		[`primo`] = {
			["name"] = "primo",
			["model"] = "primo",
			["count"] = 2,
			["price"] = 27000,
		},
		[`faction2`] = {
			["name"] = "faction2",
			["model"] = "faction2",
			["count"] = 2,
			["price"] = 10000,
		},
		[`premier`] = {
			["name"] = "premier",
			["model"] = "premier",
			["count"] = 2,
			["price"] = 17000,
		},
		[`seminole2`] = {
			["name"] = "seminole2",
			["model"] = "seminole2",
			["count"] = 2,
			["price"] = 65000,
		},
		[`baller`] = {
			["name"] = "baller",
			["model"] = "baller",
			["count"] = 2,
			["price"] = 70000,
		},
		[`ıssi2`] = {
			["name"] = "ıssi2",
			["model"] = "ıssi2",
			["count"] = 2,
			["price"] = 55000,
		},
		[`surge`] = {
			["name"] = "surge",
			["model"] = "surge",
			["count"] = 2,
			["price"] = 32000,
		},
		[`chino2`] = {
			["name"] = "chino2",
			["model"] = "chino2",
			["count"] = 2,
			["price"] = 13000,
		},
		[`radi`] = {
			["name"] = "radi",
			["model"] = "radi",
			["count"] = 2,
			["price"] = 42000,
		},
		[`asea`] = {
			["name"] = "asea",
			["model"] = "asea",
			["count"] = 2,
			["price"] = 33000,
		},
		[`bodhi2`] = {
			["name"] = "bodhi2",
			["model"] = "bodhi2",
			["count"] = 2,
			["price"] = 35000,
		},
		[`blazer`] = {
			["name"] = "blazer",
			["model"] = "blazer",
			["count"] = 2,
			["price"] = 20000,
		},
		[`virgo2`] = {
			["name"] = "virgo2",
			["model"] = "virgo2",
			["count"] = 2,
			["price"] = 10000,
		},
		[`asterope`] = {
			["name"] = "asterope",
			["model"] = "asterope",
			["count"] = 2,
			["price"] = 40000,
		},
		
	},
	["D Class"] = {
		[`kalahari`] = {
			["name"] = "kalahari",
			["model"] = "kalahari",
			["count"] = 2,
			["price"] = 6000,
		},
		[`voodoo2`] = {
			["name"] = "voodoo2",
			["model"] = "voodoo2",
			["count"] = 2,
			["price"] = 5000,
		},
		[`michelli`] = {
			["name"] = "michelli",
			["model"] = "michelli",
			["count"] = 2,
			["price"] = 5500,
		},
		[`warrener`] = {
			["name"] = "warrener",
			["model"] = "warrener",
			["count"] = 0,
			["price"] = 5500,
		},
		[`fagaloa`] = {
			["name"] = "fagaloa",
			["model"] = "fagaloa",
			["count"] = 2,
			["price"] = 8000,
		},
		[`manana2`] = {
			["name"] = "manana2",
			["model"] = "manana2",
			["count"] = 2,
			["price"] = 7000,
		},
		[`stratum`] = {
			["name"] = "stratum",
			["model"] = "stratum",
			["count"] = 2,
			["price"] = 15000,
		},
		[`dloader`] = {
			["name"] = "dloader",
			["model"] = "dloader",
			["count"] = 2,
			["price"] = 6000,
		},
		[`camper`] = {
			["name"] = "camper",
			["model"] = "camper",
			["count"] = 2,
			["price"] = 12500,
		},
		[`taco`] = {
			["name"] = "taco",
			["model"] = "taco",
			["count"] = 2,
			["price"] = 15000,
		},
		[`panto`] = {
			["name"] = "panto",
			["model"] = "panto",
			["count"] = 2,
			["price"] = 3000,
		},
		[`ratloader`] = {
			["name"] = "ratloader",
			["model"] = "ratloader",
			["count"] = 2,
			["price"] = 2500,
		},
		[`ıngot`] = {
			["name"] = "ıngot",
			["model"] = "ıngot",
			["count"] = 2,
			["price"] = 16000,
		},
		[`emperor`] = {
			["name"] = "emperor",
			["model"] = "emperor",
			["count"] = 2,
			["price"] = 8000,
		},
		[`manana`] = {
			["name"] = "manana",
			["model"] = "manana",
			["count"] = 2,
			["price"] = 11000,
		},
		[`regina`] = {
			["name"] = "regina",
			["model"] = "regina",
			["count"] = 2,
			["price"] = 8000,
		},
		[`cheburek`] = {
			["name"] = "cheburek",
			["model"] = "cheburek",
			["count"] = 2,
			["price"] = 6235,
		},
		[`journey`] = {
			["name"] = "journey",
			["model"] = "journey",
			["count"] = 2,
			["price"] = 3535,
		},
		[`emperor2`] = {
			["name"] = "emperor2",
			["model"] = "emperor2",
			["count"] = 2,
			["price"] = 13000,
		},
	},
	["İş Aracı"] = {
		[`youga`] = {
			["name"] = "youga",
			["model"] = "youga",
			["count"] = 2,
			["price"] = 7000,
		},
		[`speedo4`] = {
			["name"] = "speedo4",
			["model"] = "speedo4",
			["count"] = 2,
			["price"] = 7500,
		},
		[`burrito4`] = {
			["name"] = "burrito4",
			["model"] = "burrito4",
			["count"] = 2,
			["price"] = 7500,
		}, 
		[`youga2`] = {
			["name"] = "youga2",
			["model"] = "youga2",
			["count"] = 2,
			["price"] = 9000,
		},
		[`paradise`] = {
			["name"] = "paradise",
			["model"] = "paradise",
			["count"] = 2,
			["price"] = 8500,
		},
		[`bison3`] = {
			["name"] = "bison3",
			["model"] = "bison3",
			["count"] = 2,
			["price"] = 8700,
		},
		[`bison2`] = {
			["name"] = "bison2",
			["model"] = "bison2",
			["count"] = 2,
			["price"] = 8600,
		},
		[`burrito`] = {
			["name"] = "burrito",
			["model"] = "burrito",
			["count"] = 2,
			["price"] = 6000,
		},
		[`pony`] = {
			["name"] = "pony",
			["model"] = "pony",
			["count"] = 2,
			["price"] = 6500,
		},
		[`speedo`] = {
			["name"] = "speedo",
			["model"] = "speedo",
			["count"] = 2,
			["price"] = 7500,
		},
		[`bison`] = {
			["name"] = "bison",
			["model"] = "bison",
			["count"] = 2,
			["price"] = 10000,
		},
		[`burrito3`] = {
			["name"] = "burrito3",
			["model"] = "burrito3",
			["count"] = 2,
			["price"] = 7000,
		},
		[`burrito2`] = {
			["name"] = "burrito2",
			["model"] = "burrito2",
			["count"] = 2,
			["price"] = 6500,
		},
		[`rumpo2`] = {
			["name"] = "rumpo2",
			["model"] = "rumpo2",
			["count"] = 2,
			["price"] = 8500,
		},
	}
}